// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: peertopeer.proto

package peertopeer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_INCOMING_MESSAGE MessageType = 0
	MessageType_INCOMING_STREAM  MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "INCOMING_MESSAGE",
		1: "INCOMING_STREAM",
	}
	MessageType_value = map[string]int32{
		"INCOMING_MESSAGE": 0,
		"INCOMING_STREAM":  1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_peertopeer_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_peertopeer_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_peertopeer_proto_rawDescGZIP(), []int{0}
}

type Rpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Types that are assignable to Payload:
	//	*Rpc_StoreFile
	//	*Rpc_GetFile
	//	*Rpc_FileChunk
	Payload isRpc_Payload `protobuf_oneof:"payload"`
	Stream  bool          `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *Rpc) Reset() {
	*x = Rpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peertopeer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc) ProtoMessage() {}

func (x *Rpc) ProtoReflect() protoreflect.Message {
	mi := &file_peertopeer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc.ProtoReflect.Descriptor instead.
func (*Rpc) Descriptor() ([]byte, []int) {
	return file_peertopeer_proto_rawDescGZIP(), []int{0}
}

func (x *Rpc) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (m *Rpc) GetPayload() isRpc_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Rpc) GetStoreFile() *MessageStoreFile {
	if x, ok := x.GetPayload().(*Rpc_StoreFile); ok {
		return x.StoreFile
	}
	return nil
}

func (x *Rpc) GetGetFile() *MessageGetFile {
	if x, ok := x.GetPayload().(*Rpc_GetFile); ok {
		return x.GetFile
	}
	return nil
}

func (x *Rpc) GetFileChunk() *FileChunk {
	if x, ok := x.GetPayload().(*Rpc_FileChunk); ok {
		return x.FileChunk
	}
	return nil
}

func (x *Rpc) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type isRpc_Payload interface {
	isRpc_Payload()
}

type Rpc_StoreFile struct {
	StoreFile *MessageStoreFile `protobuf:"bytes,2,opt,name=store_file,json=storeFile,proto3,oneof"`
}

type Rpc_GetFile struct {
	GetFile *MessageGetFile `protobuf:"bytes,3,opt,name=get_file,json=getFile,proto3,oneof"`
}

type Rpc_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,4,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

func (*Rpc_StoreFile) isRpc_Payload() {}

func (*Rpc_GetFile) isRpc_Payload() {}

func (*Rpc_FileChunk) isRpc_Payload() {}

type MessageStoreFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *MessageStoreFile) Reset() {
	*x = MessageStoreFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peertopeer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageStoreFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStoreFile) ProtoMessage() {}

func (x *MessageStoreFile) ProtoReflect() protoreflect.Message {
	mi := &file_peertopeer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStoreFile.ProtoReflect.Descriptor instead.
func (*MessageStoreFile) Descriptor() ([]byte, []int) {
	return file_peertopeer_proto_rawDescGZIP(), []int{1}
}

func (x *MessageStoreFile) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MessageStoreFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MessageGetFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MessageGetFile) Reset() {
	*x = MessageGetFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peertopeer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageGetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGetFile) ProtoMessage() {}

func (x *MessageGetFile) ProtoReflect() protoreflect.Message {
	mi := &file_peertopeer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGetFile.ProtoReflect.Descriptor instead.
func (*MessageGetFile) Descriptor() ([]byte, []int) {
	return file_peertopeer_proto_rawDescGZIP(), []int{2}
}

func (x *MessageGetFile) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Offset  int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peertopeer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_peertopeer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_peertopeer_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_peertopeer_proto protoreflect.FileDescriptor

var file_peertopeer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x65, 0x65, 0x72, 0x74, 0x6f, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x74, 0x6f, 0x70, 0x65, 0x65, 0x72, 0x22, 0xec,
	0x01, 0x0a, 0x03, 0x52, 0x70, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x3d, 0x0a, 0x0a, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x65, 0x65, 0x72, 0x74, 0x6f, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x09,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x67, 0x65, 0x74,
	0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x65,
	0x65, 0x72, 0x74, 0x6f, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x07, 0x67, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x74, 0x6f, 0x70,
	0x65, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x38, 0x0a,
	0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3d, 0x0a, 0x09, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x2a, 0x38, 0x0a, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x43,
	0x4f, 0x4d, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x43, 0x4f, 0x4d, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x52, 0x45,
	0x41, 0x4d, 0x10, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x74, 0x6f,
	0x70, 0x65, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peertopeer_proto_rawDescOnce sync.Once
	file_peertopeer_proto_rawDescData = file_peertopeer_proto_rawDesc
)

func file_peertopeer_proto_rawDescGZIP() []byte {
	file_peertopeer_proto_rawDescOnce.Do(func() {
		file_peertopeer_proto_rawDescData = protoimpl.X.CompressGZIP(file_peertopeer_proto_rawDescData)
	})
	return file_peertopeer_proto_rawDescData
}

var file_peertopeer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peertopeer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_peertopeer_proto_goTypes = []interface{}{
	(MessageType)(0),         // 0: peertopeer.MessageType
	(*Rpc)(nil),              // 1: peertopeer.Rpc
	(*MessageStoreFile)(nil), // 2: peertopeer.MessageStoreFile
	(*MessageGetFile)(nil),   // 3: peertopeer.MessageGetFile
	(*FileChunk)(nil),        // 4: peertopeer.FileChunk
}
var file_peertopeer_proto_depIdxs = []int32{
	2, // 0: peertopeer.Rpc.store_file:type_name -> peertopeer.MessageStoreFile
	3, // 1: peertopeer.Rpc.get_file:type_name -> peertopeer.MessageGetFile
	4, // 2: peertopeer.Rpc.file_chunk:type_name -> peertopeer.FileChunk
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_peertopeer_proto_init() }
func file_peertopeer_proto_init() {
	if File_peertopeer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peertopeer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peertopeer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageStoreFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peertopeer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageGetFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peertopeer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_peertopeer_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Rpc_StoreFile)(nil),
		(*Rpc_GetFile)(nil),
		(*Rpc_FileChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peertopeer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peertopeer_proto_goTypes,
		DependencyIndexes: file_peertopeer_proto_depIdxs,
		EnumInfos:         file_peertopeer_proto_enumTypes,
		MessageInfos:      file_peertopeer_proto_msgTypes,
	}.Build()
	File_peertopeer_proto = out.File
	file_peertopeer_proto_rawDesc = nil
	file_peertopeer_proto_goTypes = nil
	file_peertopeer_proto_depIdxs = nil
}
