# Test configuration for single-leader mode
mode: "single-leader"
role: "leader"
node_id: "node1"

# Peer nodes in the cluster
peer_nodes:
  - "localhost:3001"
  - "localhost:3002"

# Network Configuration
network:
  listen_address: ":3000"
  advertise_address: "localhost:3000"
  dial_timeout: "5s"
  read_timeout: "5s"
  write_timeout: "5s"
  handshake_timeout: "3s"
  max_retries: 3
  retry_backoff: "1s"

# Storage Configuration
storage:
  storage_root: "/tmp/dfs/data"
  metadata_root: "/tmp/dfs/metadata"
  default_file_mode: 0644
  max_file_size: 1073741824  # 1GB in bytes

# Replication Configuration
replication:
  factor: 3
  async_replication: false
  async_queue_size: 1000
  consistency_level: "quorum"